import './global.css'

import { GeistSans } from 'geist/font/sans'
import { type Metadata } from 'next'

import { TRPCReactProvider } from '~/trpc/react'

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app, and manually crafted to add Panda CSS',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
} satisfies Metadata

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={GeistSans.variable}>
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  )
}
